# Generated by Django 4.2.3 on 2023-07-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='static/img/img-01.jpg', null=True, upload_to='post_images'),
        ),
    ]
